name: Enable Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  enable-auto-merge:
    name: Enable Auto Merge
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'auto-merge')
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Enable auto-merge for PR
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          
          echo "Enabling auto-merge for PR #${pr_number}"
          
          # Enable GitHub's built-in auto-merge feature with squash merge
          gh pr merge ${pr_number} --auto --squash --delete-branch
          
          echo "✅ Auto-merge enabled for PR #${pr_number}"
          echo "The PR will be automatically merged when all checks pass and requirements are met."
          
          # Add a comment to notify about auto-merge being enabled
          gh pr comment ${pr_number} --body "🤖 Auto-merge has been enabled for this PR with the following settings:
          - **Merge method**: Squash and merge
          - **Delete branch**: Yes
          - **Conditions**: All status checks must pass and required reviews must be approved
          
          The PR will be automatically merged when all conditions are met."
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  disable-auto-merge:
    name: Disable Auto Merge
    runs-on: ubuntu-latest
    if: |
      github.event.action == 'unlabeled' && 
      github.event.label.name == 'auto-merge'
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Disable auto-merge for PR
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          
          echo "Disabling auto-merge for PR #${pr_number}"
          
          # Disable GitHub's auto-merge feature
          gh pr merge ${pr_number} --disable-auto
          
          echo "❌ Auto-merge disabled for PR #${pr_number}"
          
          # Add a comment to notify about auto-merge being disabled
          gh pr comment ${pr_number} --body "🤖 Auto-merge has been disabled for this PR. The PR will need to be merged manually."
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}